# RAG System Configuration
embeddings:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cpu" # Changed from cuda to cpu for Mac compatibility
  batch_size: 32

vector_store:
  type: "faiss" # Options: faiss, chromadb
  index_path: "./data/rag_index/"
  dimension: 384 # Embedding dimension for all-MiniLM-L6-v2

# ChromaDB alternative settings
chromadb:
  persist_directory: "./data/chromadb/"
  collection_name: "legal_documents"

# Document processing
documents:
  chunk_size: 1000
  chunk_overlap: 200
  separators: ["\n\n", "\n", ".", "!", "?"]

# Retrieval settings
retrieval:
  top_k: 5
  similarity_threshold: 0.7
  search_type: "similarity" # Options: similarity, mmr

# Reranking (optional)
reranking:
  enabled: false
  model_name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  top_k_rerank: 3

# Generation settings
generation:
  max_context_length: 2048
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.9
